# Brosoft-Dao CI script

variables:
  BROSOFT_DAO_ENV: gitlab
  POSTGRES_DB: test
  POSTGRES_USER: gitlab
  POSTGRES_PASSWORD: gitlab

before_script:
  - apt-get -qq update
  - apt-get -qq install -y openjdk-8-jdk-headless
  - apt-get -qq install -y maven
  - mvn -q install

cucumber:
  services:
    - mongo:latest
    - postgres:latest
  script:
    - mvn test

