# Brosoft-Dao CI script
image:
  name: ascdc/jdk8

variables:
  BROSOFT_DAO_ENV: gitlab
  POSTGRES_DB: test
  POSTGRES_USER: gitlab
  POSTGRES_PASSWORD: gitlab

before_script:
  - apt-get update
  - apt-get install -y maven
  - mvn install

cucumber:
  services:
    - mongo:latest
    - postgres:latest
  script:
    - mvn test

