# Brosoft-Dao CI script

variables:
  BROSOFT_DAO_ENV: gitlab
  POSTGRES_DB: test
  POSTGRES_USER: gitlab
  POSTGRES_PASSWORD: gitlab

before_script:
  - apt update
  - apt install -y openjdk-8-jdk
  - apt install -y maven
  - mvn install

cucumber:
  services:
    - mongo:latest
    - postgres:latest
  script:
    - mvn test

